export const WORD_LIBRARY = [
  { word: 'HELLO', hint: 'A common greeting' },
  { word: 'WORLD', hint: 'The planet we live on' },
  { word: 'LOVE', hint: 'A deep affection' },
  { word: 'PEACE', hint: 'Freedom from disturbance' },
  { word: 'HAPPY', hint: 'Feeling joy' },
  { word: 'LEARN', hint: 'To gain knowledge' },
  { word: 'SIGN', hint: 'A gesture or symbol' },
  { word: 'HAND', hint: 'Part of the body' },
  { word: 'GOOD', hint: 'Positive quality' },
  { word: 'HELP', hint: 'To assist someone' },
  { word: 'THANK', hint: 'To express gratitude' },
  { word: 'FRIEND', hint: 'Someone you care about' },
  { word: 'FAMILY', hint: 'Related people' },
  { word: 'SCHOOL', hint: 'Place of learning' },
  { word: 'WORK', hint: 'To perform tasks' },
  { word: 'PLAY', hint: 'To have fun' },
  { word: 'CAT', hint: 'A furry pet' },
  { word: 'DOG', hint: 'A loyal pet' },
  { word: 'WATER', hint: 'Essential liquid' },
  { word: 'FOOD', hint: 'What we eat' },
];
